#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt update
sudo apt install nginx -y
echo "Redirecting to another page..." | sudo tee /var/www/html/redirect.html
sudo bash -c 'cat > /etc/nginx/sites-available/redirect' <<EOL
server {
    listen 80;
    server_name japhetaline.tech www.japhetaline.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4

    location / {
        # Your regular location block configuration
        root /var/www/html;
        index index.html index.htm;
    }
}
EOL
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl reload nginx
