#!/usr/bin/env bash
# Automatizing the nginx configuration
sudo apt-get -y update
sudo apt-get -y install nginx
echo "add_header X-Served-By \$263828-web-01;" | sudo tee -a /etc/nginx/nginx.conf > /dev/null
sudo systemctl reload nginx
