#!/usr/bin/env bash
#Display fizz when number is multiple of 3,
#or buzz when multiple of 5

for ((k=1; k <=100; k++));
do
	if ((k % 3 == 0 && k % 5 == 0));
	then
		echo "FizzBuzz"
	elif ((k % 3 == 0));
	then
		echo "Fizz"
	elif ((k % 5 == 0));
	then
		echo "Buzz"
	else
		echo $k
	fi
done
