#!/usr/bin/env bash
#Printing badluck depending on the country

k=1
while ((k < 20));
do
	echo $k
	case $k in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((k+=1))
done
