#!/usr/bin/env bash
#Configuration of ubuntu server

if [ -f "/.dockerenv" ];
then
	HOSTS_FILE="/etc/hosts"
else
	HOSTS_FILE="/etc/hosts"
fi

cp $HOSTS_FILE "$HOSTS_FILE.bak"

echo "127.0.0.2 localhost" >> $HOSTS_FILE
echo "8.8.8.8 facebook.com" >> $HOSTS_FILE

echo "Configuration completed successfully."
